### ISSUE TITLE
Doesn't work with ptpv2d P2P mode

### ISSUE THREAD

**Issue by andrewburnheimer** [andrewburnheimer/ptpop#3]
Following error thrown:

```
Tue Oct 25 2016 05:09:51.909 UTC
remote          Dly St Dom Pr1  Cl Acc   Var  Pr2       Uniq       SyncT  DlyT  AnnT
====================================================================================

Unhandled exception in thread started by <built-in method loop of pcap.pcap object at 0xb677a7c8>
Traceback (most recent call last):
  File "pcap.pyx", line 335, in pcap.pcap.loop (pcap.c:3473)
  File "build/bdist.linux-armv6l/egg/ptpop/Listener.py", line 74, in _handle_received_packet
  File "build/bdist.linux-armv6l/egg/ptpop/PtpNeighbor.py", line 34, in __init__
  File "build/bdist.linux-armv6l/egg/ptpop/PtpNeighbor.py", line 56, in new_announce_message
  File "build/bdist.linux-armv6l/egg/ptpop/AnnounceMessage.py", line 201, in __init__
struct.error: unpack requires a string argument of length 2
```

**Comment by andrewburnheimer** [comment]
PTPD started with: `/usr/sbin/ptpd -c -t -d -b eth5`
